
provisioner:
  name: terraform

platforms:
  - name: local

verifier:
  name: terraform
  systems:
    - name: system
      backend: gcp

suites:
  - name: full
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/full
